local opt = vim.opt

opt.cmdheight = 2
opt.wrap = false
opt.colorcolumn = "95"
opt.tabstop = 4
opt.shiftwidth = 4
opt.softtabstop = 4
opt.expandtab = true
opt.scrolloff = 8
opt.nu = true
opt.relativenumber = true
opt.hlsearch = true
opt.incsearch = true
opt.termguicolors = true
opt.signcolumn = "yes"
opt.swapfile = false
opt.backup = false
opt.cursorline = true
opt.completeopt = "menuone,noselect"
opt.clipboard = "unnamedplus"
