vim.g.mapleader = " "
vim.keymap.set("i", "<C-c>", "<Esc>")
vim.keymap.set("i", "{", "{}<left>")
vim.keymap.set("i", "[", "[]<left>")
vim.keymap.set("i", "(", "()<left>")
vim.keymap.set("i", "<C-t>", "<C-x><C-o>")
vim.keymap.set("i", "<C-e>", "<C-y>", { remap = true })
vim.keymap.set("n", "<leader>n", ":bnext<CR>")
vim.keymap.set("n", "<leader>p", ":bprevious<CR>")
vim.keymap.set("n", "<leader>d", ":bdelete<CR>")
vim.keymap.set("n", "<leader>c", "gcc")
vim.keymap.set("n", "<leader>m", ":MarkdownPreview<CR>")
vim.keymap.set("n", "<leader>t", ":terminal<CR>")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("v", "<leader>y", "\"+y")
vim.keymap.set("t", "<Esc>", "<C-\\><C-n>")
